// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package catalog

type CatalogSeries struct {
	ID                        *string                  `json:"id"`
	Name                      *string                  `json:"name"`
	Description               *string                  `json:"description"`
	Shortname                 *string                  `json:"shortname"`
	ImageGroup                *string                  `json:"image_group"`
	CatalogSeriesCategoryList []*CatalogSeriesCategory `json:"catalog_series_category_list"`
}

type CatalogSeriesCategory struct {
	ID                            *string                      `json:"id"`
	CatalogSeriesID               *string                      `json:"catalog_series_id"`
	Name                          *string                      `json:"name"`
	Description                   *string                      `json:"description"`
	Shortname                     *string                      `json:"shortname"`
	ImageGroup                    *string                      `json:"image_group"`
	CatalogSeriesCategoryPartList []*CatalogSeriesCategoryPart `json:"catalog_series_category_part_list"`
}

type CatalogSeriesCategoryPart struct {
	ID                                   *string                             `json:"id"`
	CatalogSeriesCategoryID              *string                             `json:"catalog_series_category_id"`
	Name                                 *string                             `json:"name"`
	Description                          *string                             `json:"description"`
	Shortname                            *string                             `json:"shortname"`
	ImageGroup                           *string                             `json:"image_group"`
	Code                                 *string                             `json:"code"`
	Internalcode                         *string                             `json:"internalcode"`
	Tag                                  *string                             `json:"tag"`
	Price                                *int                                `json:"price"`
	CatalogSeriesCategoryPartVersionList []*CatalogSeriesCategoryPartVersion `json:"catalog_series_category_part_version_list"`
}

type CatalogSeriesCategoryPartVersion struct {
	ID                          *string `json:"id"`
	CatalogSeriesCategoryPartID *string `json:"catalog_series_category_part_id"`
	Code                        *string `json:"code"`
	Internalcode                *string `json:"internalcode"`
	Description                 *string `json:"description"`
	ImageGroup                  *string `json:"image_group"`
	Price                       *int    `json:"price"`
}
