// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package catalog

type CatalogSeries struct {
	ID          *string                  `json:"id"`
	Name        *string                  `json:"name"`
	Description *string                  `json:"description"`
	Shortname   *string                  `json:"shortname"`
	ImageGroup  *string                  `json:"image_group"`
	Categories  []*CatalogSeriesCategory `json:"categories"`
}

type CatalogSeriesCategory struct {
	ID          *string                      `json:"id"`
	Name        *string                      `json:"name"`
	Description *string                      `json:"description"`
	Shortname   *string                      `json:"shortname"`
	ImageGroup  *string                      `json:"image_group"`
	Parts       []*CatalogSeriesCategoryPart `json:"parts"`
}

type CatalogSeriesCategoryPart struct {
	ID          *string                             `json:"id"`
	Name        *string                             `json:"name"`
	Description *string                             `json:"description"`
	Shortname   *string                             `json:"shortname"`
	ImageGroup  *string                             `json:"image_group"`
	Versions    []*CatalogSeriesCategoryPartVersion `json:"versions"`
}

type CatalogSeriesCategoryPartVersion struct {
	ID          *string `json:"id"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Shortname   *string `json:"shortname"`
	ImageGroup  *string `json:"image_group"`
	Price       *int    `json:"price"`
}
